---
  - name: Install Haproxy server
    package:
            name: haproxy
            state: latest

  - name: copy configuration file in haproxy
    template:
                 src: haproxy.cfg
                 dest: /etc/haproxy/haproxy.cfg
    notify:
                 - Restart haproxy
  - name: start firewalld
    service:
                name: firewalld
                state: started

  - name: Add rules in firewalld for haproxy
    ansible.posix.firewalld:
                 port: "{{ LoadBlancer_port }}/tcp"
                 state: enabled
                 immediate: yes
                 permanent: yes


  - name: start HAPROXY
    service:
                 name: haproxy
                 state: started
                 enabled: yes
